name = "BlockBootstrap"
uuid = "483824fe-0d37-42f7-bb97-b8abf41a4f6a"
authors = ["william davis <williamjsdavis@berkeley.edu>"]
version = "0.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.3.1"
